services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    env_file: .env
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  mirakc:
    image: mirakc/mirakc:latest
    volumes:
      - ./mirakc-scripts:/scripts
      - mirakc-data:/var/lib/mirakc
    entrypoint: ['/scripts/init-mirakc.sh']
    env_file: .env

volumes:
  mirakc-data:
    driver: local
