services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    env_file: .env
  mirakc:
    build:
      context: ./mirakc
      dockerfile: Dockerfile
    volumes:
      - mirakc-data:/var/lib/mirakc/epg
      - ./data:/data
    env_file: .env
    environment:
      - TZ=Asia/Tokyo
      - MIRAKC_DEBUG_CHILD_PROCESS=1
      - MIRAKC_ARIB_LOG=warn,filter-program=debug

volumes:
  mirakc-data:
    driver: local
