name: Wasm

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.3
          actions-cache-folder: 'emsdk-cache'

      - name: Build
        run: yarn cmake:config
        run: yarn cmake:build
