name: Release to release branch

on:
  release:
    types: [published]

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: DeeDeeG/rebase-github-action@v1.0
        with:
          head_branch: release
          base_ref: ${{ github.ref }}
