name: Release to release branch

on:
  release:
    types: [published]

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: 'v(?<version>.*)'

      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'release'
          commit_message_template: '[Automated] Released from {source_ref}'
      - uses: cardinalby/git-tag-action@master
        env:
          TAG: release-v${{ steps.tagName.outputs.version }}
          GITHUB_TOKEN: ${{ github.token }}
