name: Release to release branch

on:
  release:
    types: [published]

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Embraser01/update-git-branch-action@v1.0.0
        with:
          branch: release
          force: 1 # To push-force to the branch
          githubToken: ${{ github.token }} # Github Token
